package banner

import (
	"fmt"
	"os"
	"runtime"
	"time"
)

// Variant1 - Full screen modern banner with detailed info
func Variant1() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("    ╔═══════════════════════════════════════════════════════════════════════════════════╗")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║        ██████╗ ██╗   ██╗ █████╗ ███████╗ █████╗  █████╗ ██████╗                   ║")
	fmt.Println("    ║       ██╔═══██╗██║   ██║██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗                  ║")
	fmt.Println("    ║       ██║   ██║██║   ██║███████║  ███╔╝ ███████║███████║██████╔╝                  ║")
	fmt.Println("    ║       ██║▄▄ ██║██║   ██║██╔══██║ ███╔╝  ██╔══██║██╔══██║██╔══██╗                  ║")
	fmt.Println("    ║       ╚██████╔╝╚██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║                  ║")
	fmt.Println("    ║        ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                  ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║                        Media Control & System Manager                             ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║  ════════════════════════════════════════════════════════════════════════════════ ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Printf("    ║    Version:       %-58s      ║\n", "0.0.1.3 (Beta)")
	fmt.Printf("    ║    Build Date:    %-58s      ║\n", time.Now().Format("2006-01-02 15:04:05"))
	fmt.Printf("    ║    Runtime:       %-58s      ║\n", runtime.Version())
	fmt.Printf("    ║    Platform:      %-58s      ║\n", runtime.GOOS+"/"+runtime.GOARCH)
	fmt.Printf("    ║    Hostname:      %-58s      ║\n", hostname)
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║  ════════════════════════════════════════════════════════════════════════════════ ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║    Features:                                                                      ║")
	fmt.Println("    ║      🎵  Media Player Control       📡  WebSocket Real-time Updates               ║")
	fmt.Println("    ║      🔊  Volume Management          🌐  RESTful API (v0.1)                        ║")
	fmt.Println("    ║      📱  Cross-Platform Support     🔐  Token-based Authentication                ║")
	fmt.Println("    ║      🎧  Spotify Integration        📊  System Information API                    ║")
	fmt.Println("    ║      🔌  WiFi & Bluetooth Info      💾  SQLite Database                           ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║  ════════════════════════════════════════════════════════════════════════════════ ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ║    © 2025 Swapnil Ingle              Licensed under the MIT License               ║")
	fmt.Println("    ║    Project: Quazaar                  Repository: https://github.com/codershubinc  ║")
	fmt.Println("    ║                                                                                   ║")
	fmt.Println("    ╚═══════════════════════════════════════════════════════════════════════════════════╝")
	fmt.Print("\n")
}

// Variant2 - Full width gradient with system stats
func Variant2() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("  ╭─────────────────────────────────────────────────────────────────────────────────╮")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │                    ░░░░░░▒▒▒▒▒▒▓▓▓▓▓▓  QUAZAAR  ▓▓▓▓▓▓▒▒▒▒▒▒░░░░░░              │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │                         Media Control & System Manager                          │")
	fmt.Println("  │                                  Beta v0.0.1.3                                  │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │")
	fmt.Println("  │                                                                                 │")
	fmt.Printf("  │  📦 Runtime:    %-65s │\n", runtime.Version())
	fmt.Printf("  │  🖥️  Platform:   %-65s │\n", runtime.GOOS+"/"+runtime.GOARCH)
	fmt.Printf("  │  🏠 Hostname:   %-65s │\n", hostname)
	fmt.Printf("  │  ⏰ Started:    %-65s │\n", time.Now().Format("Mon Jan 02, 2006 at 15:04:05"))
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │  🎵  Media Player Control          🔊  Volume Management                        │")
	fmt.Println("  │  📡  WebSocket Real-time           🌐  RESTful API Endpoints                    │")
	fmt.Println("  │  🎧  Spotify Integration           🔐  Secure Authentication                    │")
	fmt.Println("  │  📱  Cross-Platform (Linux/Win)    💾  SQLite Database                          │")
	fmt.Println("  │  🔌  Network Information           📊  System Monitoring                        │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  │  © 2025 Swapnil Ingle  •  MIT Licensed  •  Project: Quazaar                    │")
	fmt.Println("  │                                                                                 │")
	fmt.Println("  ╰─────────────────────────────────────────────────────────────────────────────────╯")
	fmt.Print("\n")
}

// Variant3 - Bold block letters with full info
func Variant3() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("    ╔════════════════════════════════════════════════════════════════════════════╗")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║       ██████╗ ██╗   ██╗ █████╗ ███████╗ █████╗  █████╗ ██████╗            ║")
	fmt.Println("    ║      ██╔═══██╗██║   ██║██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗           ║")
	fmt.Println("    ║      ██║   ██║██║   ██║███████║  ███╔╝ ███████║███████║██████╔╝           ║")
	fmt.Println("    ║      ██║▄▄ ██║██║   ██║██╔══██║ ███╔╝  ██╔══██║██╔══██║██╔══██╗           ║")
	fmt.Println("    ║      ╚██████╔╝╚██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║           ║")
	fmt.Println("    ║       ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝           ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║                    Media Control & System Manager                          ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║  ════════════════════════════════════════════════════════════════════════ ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Printf("    ║  📌 Version:  %-62s║\n", "0.0.1.3 (Beta)")
	fmt.Printf("    ║  🖥️  System:   %-62s║\n", runtime.GOOS+"/"+runtime.GOARCH+" • "+runtime.Version())
	fmt.Printf("    ║  🏠 Host:     %-62s║\n", hostname)
	fmt.Printf("    ║  🕐 Time:     %-62s║\n", time.Now().Format("2006-01-02 15:04:05 MST"))
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║  ════════════════════════════════════════════════════════════════════════ ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║  🎵  Media Player Control       📡  WebSocket Real-time Updates            ║")
	fmt.Println("    ║  🔊  Volume Management          🌐  RESTful API (v0.1)                     ║")
	fmt.Println("    ║  📱  Cross-Platform Support     🔐  Token-based Authentication             ║")
	fmt.Println("    ║  🎧  Spotify Integration        📊  System Information API                 ║")
	fmt.Println("    ║  🔌  WiFi & Bluetooth Info      💾  SQLite Database                        ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║  ════════════════════════════════════════════════════════════════════════ ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ║  © 2025 Swapnil Ingle • MIT Licensed • Project: Quazaar                   ║")
	fmt.Println("    ║                                                                            ║")
	fmt.Println("    ╚════════════════════════════════════════════════════════════════════════════╝")
	fmt.Print("\n")
}

// Variant4 - Compact modern with details
func Variant4() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("         ┌───────────────────────────────────────────────────────────────────┐")
	fmt.Println("         │                                                                   │")
	fmt.Println("         │      ██████╗ ██╗   ██╗ █████╗ ███████╗ █████╗  █████╗ ██████╗    │")
	fmt.Println("         │     ██╔═══██╗██║   ██║██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗   │")
	fmt.Println("         │     ██║   ██║██║   ██║███████║  ███╔╝ ███████║███████║██████╔╝   │")
	fmt.Println("         │     ██║▄▄ ██║██║   ██║██╔══██║ ███╔╝  ██╔══██║██╔══██║██╔══██╗   │")
	fmt.Println("         │     ╚██████╔╝╚██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║   │")
	fmt.Println("         │      ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝   │")
	fmt.Println("         │                                                                   │")
	fmt.Println("         │                    Media Control & System Manager                 │")
	fmt.Println("         │                                                                   │")
	fmt.Println("         │  ═══════════════════════════════════════════════════════════════  │")
	fmt.Println("         │                                                                   │")
	fmt.Printf("         │  Version:  %-55s│\n", "0.0.1.3 (Beta)")
	fmt.Printf("         │  Runtime:  %-55s│\n", runtime.Version())
	fmt.Printf("         │  OS/Arch:  %-55s│\n", runtime.GOOS+"/"+runtime.GOARCH)
	fmt.Printf("         │  Host:     %-55s│\n", hostname)
	fmt.Printf("         │  Started:  %-55s│\n", time.Now().Format("15:04:05 on Jan 02, 2006"))
	fmt.Println("         │                                                                   │")
	fmt.Println("         │  ═══════════════════════════════════════════════════════════════  │")
	fmt.Println("         │                                                                   │")
	fmt.Println("         │  Features:                                                        │")
	fmt.Println("         │    • Media Player Control (Play, Pause, Next, Previous)          │")
	fmt.Println("         │    • Real-time WebSocket Updates                                 │")
	fmt.Println("         │    • Volume Management & Audio Control                           │")
	fmt.Println("         │    • Spotify Integration & Metadata                              │")
	fmt.Println("         │    • RESTful API v0.1 Endpoints                                  │")
	fmt.Println("         │    • Token-based Authentication                                  │")
	fmt.Println("         │    • WiFi & Bluetooth Information                                │")
	fmt.Println("         │    • System Monitoring & Stats                                   │")
	fmt.Println("         │    • Cross-Platform (Linux/Windows)                              │")
	fmt.Println("         │    • SQLite Database Storage                                     │")
	fmt.Println("         │                                                                   │")
	fmt.Println("         │  ═══════════════════════════════════════════════════════════════  │")
	fmt.Println("         │                                                                   │")
	fmt.Println("         │  © 2025 Swapnil Ingle • MIT Licensed                             │")
	fmt.Println("         │  Project: Quazaar • github.com/codershubinc                      │")
	fmt.Println("         │                                                                   │")
	fmt.Println("         └───────────────────────────────────────────────────────────────────┘")
	fmt.Print("\n")
}

// Variant5 - Double border with ASCII art
func Variant5() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("  ╔══════════════════════════════════════════════════════════════════════════════╗")
	fmt.Println("  ║  ╔════════════════════════════════════════════════════════════════════════╗  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ║      ██████╗ ██╗   ██╗ █████╗ ███████╗ █████╗  █████╗ ██████╗         ║  ║")
	fmt.Println("  ║  ║     ██╔═══██╗██║   ██║██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗        ║  ║")
	fmt.Println("  ║  ║     ██║   ██║██║   ██║███████║  ███╔╝ ███████║███████║██████╔╝        ║  ║")
	fmt.Println("  ║  ║     ██║▄▄ ██║██║   ██║██╔══██║ ███╔╝  ██╔══██║██╔══██║██╔══██╗        ║  ║")
	fmt.Println("  ║  ║     ╚██████╔╝╚██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║        ║  ║")
	fmt.Println("  ║  ║      ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝        ║  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ║                  Media Control & System Manager v0.0.1.3              ║  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ╠════════════════════════════════════════════════════════════════════════╣  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Printf("  ║  ║  Runtime:   %-59s║  ║\n", runtime.Version())
	fmt.Printf("  ║  ║  Platform:  %-59s║  ║\n", runtime.GOOS+"/"+runtime.GOARCH)
	fmt.Printf("  ║  ║  Hostname:  %-59s║  ║\n", hostname)
	fmt.Printf("  ║  ║  Started:   %-59s║  ║\n", time.Now().Format("2006-01-02 at 15:04:05 MST"))
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ╠════════════════════════════════════════════════════════════════════════╣  ║")
	fmt.Println("  ║  ║  Features:                                                             ║  ║")
	fmt.Println("  ║  ║    🎵  Media Player Control       📡  WebSocket Updates                ║  ║")
	fmt.Println("  ║  ║    🔊  Volume Management          🌐  RESTful API v0.1                 ║  ║")
	fmt.Println("  ║  ║    📱  Cross-Platform Support     🔐  Authentication                    ║  ║")
	fmt.Println("  ║  ║    🎧  Spotify Integration        📊  System Information               ║  ║")
	fmt.Println("  ║  ║    🔌  Network Information        💾  SQLite Database                  ║  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ╠════════════════════════════════════════════════════════════════════════╣  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ║  © 2025 Swapnil Ingle • MIT Licensed • Project: Quazaar               ║  ║")
	fmt.Println("  ║  ║                                                                        ║  ║")
	fmt.Println("  ║  ╚════════════════════════════════════════════════════════════════════════╝  ║")
	fmt.Println("  ╚══════════════════════════════════════════════════════════════════════════════╝")
	fmt.Print("\n")
}

// Variant6 - Minimal elegant with dividers
func Variant6() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("                             ⚡ Q U A Z A A R ⚡")
	fmt.Println()
	fmt.Println("                      Media Control & System Manager")
	fmt.Println("                              Version 0.0.1.3")
	fmt.Println()
	fmt.Println("    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Printf("      Runtime:      %s\n", runtime.Version())
	fmt.Printf("      Platform:     %s/%s\n", runtime.GOOS, runtime.GOARCH)
	fmt.Printf("      Hostname:     %s\n", hostname)
	fmt.Printf("      Started:      %s\n", time.Now().Format("Monday, January 02, 2006 at 15:04:05"))
	fmt.Println()
	fmt.Println("    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("      Core Features:")
	fmt.Println("        • Media Player Control (Play, Pause, Next, Previous, Volume)")
	fmt.Println("        • Real-time WebSocket Updates for Live Media Information")
	fmt.Println("        • Spotify Integration with Rich Metadata & Artwork")
	fmt.Println("        • RESTful API v0.1 with 18+ Endpoints")
	fmt.Println("        • Secure Token-based Authentication System")
	fmt.Println("        • System Information API (WiFi, Bluetooth)")
	fmt.Println("        • Cross-Platform Support (Linux D-Bus, Windows SMTC)")
	fmt.Println("        • SQLite Database for User & Token Management")
	fmt.Println()
	fmt.Println("    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()
	fmt.Println("      © 2025 Swapnil Ingle • Licensed under MIT License")
	fmt.Println("      Project: Quazaar • github.com/codershubinc")
	fmt.Println()
	fmt.Println("    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Print("\n")
}

// Variant7 - Retro ASCII art style
func Variant7() {
	hostname, _ := os.Hostname()

	fmt.Print("\n\n")
	fmt.Println("    ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┃    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄     ┃")
	fmt.Println("    ┃    ██ ▄▄▄██ ██   ██ ▄▄▄██ ▀▀▀▀▀ ██ ▄▄▄██ ▄▄▄██ ██▀▀▀▀ ██▀▀▀█        ┃")
	fmt.Println("    ┃    ██ ▄▄▄▄█ ██   ██ ▄▄▄▄█   ▄▄   ██ ▄▄▄██ ▄▄▄██ ██     ██   █        ┃")
	fmt.Println("    ┃    ██ ▀▀▀██ ██   ██ ▀▀▀██  ▀▀▀   ██ ▀▀▀██ ▀▀▀██ ██▄▄▄▄ ██  ▄█        ┃")
	fmt.Println("    ┃    ▀▀     ▀ ▀▀▀▀▀▀▀     ▀ ▀▀▀▀▀▀ ▀▀     ▀     ▀ ▀▀▀▀▀▀ ▀▀▀▀▀         ┃")
	fmt.Println("    ┃    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀     ┃")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┃                  Media Control & System Manager                         ┃")
	fmt.Println("    ┃                         Beta Release v0.0.1.3                           ┃")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Printf("    ┃    ⚙️  Runtime:     %-52s┃\n", runtime.Version())
	fmt.Printf("    ┃    💻 Platform:    %-52s┃\n", runtime.GOOS+"/"+runtime.GOARCH)
	fmt.Printf("    ┃    🏠 Hostname:    %-52s┃\n", hostname)
	fmt.Printf("    ┃    🕒 Timestamp:   %-52s┃\n", time.Now().Format("2006-01-02 15:04:05 MST"))
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┃    🎵 Media Control    🔊 Volume Mgmt      📡 WebSocket Updates        ┃")
	fmt.Println("    ┃    🎧 Spotify API      🌐 REST API v0.1    🔐 Authentication           ┃")
	fmt.Println("    ┃    📱 Cross-Platform   🔌 Network Info     💾 SQLite DB                ┃")
	fmt.Println("    ┃    📊 System Stats     🛡️  Secure Tokens    ⚡ Real-time Data           ┃")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┃    © 2025 Swapnil Ingle                                                 ┃")
	fmt.Println("    ┃    Licensed under MIT License                                           ┃")
	fmt.Println("    ┃    Project: Quazaar • github.com/codershubinc                           ┃")
	fmt.Println("    ┃                                                                         ┃")
	fmt.Println("    ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛")
	fmt.Print("\n")
}

// Show displays the default banner (Variant1)
func Show() {
	Variant1()
	// Variant2()
	// Variant3()
	// Variant4()
	// Variant5()
	// Variant6()
	// Variant7()

}
