<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Use .NET 8 or higher for AOT -->
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    
    <!-- NATIVE AOT OPTIMIZATION -->
    <!-- <PublishAot>true</PublishAot> -->
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.Windows.SDK.NET.Ref" />
  </ItemGroup>

</Project>